In [1]:
import pandas as pd
import numpy as np

In [2]:

cleandf=pd.read_csv('cleandf.csv')

cleandf=cleandf.drop('Unnamed: 0', axis=1)
cleandf

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0                 30          0         2     1                          4  
1                 31          0         1     0                          0  
2                 31          0         0     0                          2  
3                 24          0         2     0                          4  
4                 30          0         2     1                          2  
..               ...        ...       ...   ...                        ...  
695               22          1         2     0                          8  
696               24          0         1     2                          3  
697               25          1         0     0                          8  
698               25          1         0     0                          2  
699               25          0         1     1                          2  

[700 rows x 15 columns]

In [3]:
cleandf['Absenteeism Time in Hours'].median()

3.0

In [4]:
cleandf['Absenteeism Time in Hours'].mean()

6.761428571428572

In [5]:
#cleandf['Absenteeism Time in Hours']=cleandf['Absenteeism Time in Hours'].apply(lambda x: 0 if x<=cleandf['Absenteeism Time in Hours'].median() else 1)
cleandf['Absenteeism Time in Hours']=np.where(cleandf['Absenteeism Time in Hours']>cleandf['Absenteeism Time in Hours'].median(),1,0)
cleandf

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0                 30          0         2     1                          1  
1                 31          0         1     0                          0  
2                 31          0         0     0                          0  
3                 24          0         2     0                          1  
4                 30          0         2     1                          0  
..               ...        ...       ...   ...                        ...  
695               22          1         2     0                          1  
696               24          0         1     2                          0  
697               25          1         0     0                          1  
698               25          1         0     0                          0  
699               25          0         1     1                          0  

[700 rows x 15 columns]

In [6]:
cleandf.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours'], dtype=object)

In [7]:
cleandf=cleandf[['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index',
       'Children', 'Pets', 'Absenteeism Time in Hours']]
cleandf

Reason_1  Reason_2  Reason_3  Reason_4  Education  Month Value  \
0           0         0         0         1          0            7   
1           0         0         0         0          0            7   
2           0         0         0         1          0            7   
3           1         0         0         0          0            7   
4           0         0         0         1          0            7   
..        ...       ...       ...       ...        ...          ...   
695         1         0         0         0          1            5   
696         1         0         0         0          0            5   
697         1         0         0         0          1            5   
698         0         0         0         1          1            5   
699         0         0         0         1          0            5   

     Day of the Week  Transportation Expense  Distance to Work  Age  \
0                  1                     289                36   33   
1                  1                     118                13   50   
2                  2                     179                51   38   
3                  3                     279                 5   39   
4                  3                     289                36   33   
..               ...                     ...               ...  ...   
695                2                     179                22   40   
696                2                     225                26   28   
697                3                     330                16   28   
698                3                     235                16   32   
699                3                     291                31   40   

     Daily Work Load Average  Body Mass Index  Children  Pets  \
0                    239.554               30         2     1   
1                    239.554               31         1     0   
2                    239.554               31         0     0   
3                    239.554               24         2     0   
4                    239.554               30         2     1   
..                       ...              ...       ...   ...   
695                  237.656               22         2     0   
696                  237.656               24         1     2   
697                  237.656               25         0     0   
698                  237.656               25         0     0   
699                  237.656               25         1     1   

     Absenteeism Time in Hours  
0                            1  
1                            0  
2                            0  
3                            1  
4                            0  
..                         ...  
695                          1  
696                          0  
697                          1  
698                          0  
699                          0  

[700 rows x 15 columns]

In [8]:
y=cleandf['Absenteeism Time in Hours']
x=cleandf.drop('Absenteeism Time in Hours', axis=1)

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=101)
x_train

Reason_1  Reason_2  Reason_3  Reason_4  Education  Month Value  \
448         0         0         0         1          0           12   
174         0         0         0         1          0            3   
388         0         0         0         1          0            2   
80          0         0         0         1          0            5   
98          0         0         0         1          0            1   
..        ...       ...       ...       ...        ...          ...   
75          1         0         0         0          0           10   
599         0         0         0         1          0            2   
575         0         0         0         1          1           10   
337         0         0         0         0          0           11   
523         1         0         0         0          0           10   

     Day of the Week  Transportation Expense  Distance to Work  Age  \
448                2                     179                51   38   
174                2                     225                26   28   
388                2                     179                51   38   
80                 0                     179                51   38   
98                 0                     248                25   47   
..               ...                     ...               ...  ...   
75                 1                     291                31   40   
599                3                     225                26   28   
575                0                     179                22   40   
337                1                     279                 5   39   
523                3                     369                17   31   

     Daily Work Load Average  Body Mass Index  Children  Pets  
448                  253.957               31         0     0  
174                  343.253               24         1     2  
388                  251.818               31         0     0  
80                   306.345               31         0     0  
98                   261.306               32         2     1  
..                       ...              ...       ...   ...  
75                   253.465               25         1     1  
599                  264.249               24         1     2  
575                  313.532               22         2     0  
337                  284.031               24         2     0  
523                  284.853               25         3     0  

[560 rows x 14 columns]

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler=StandardScaler()

In [12]:
dummies=x_train[['Reason_1','Reason_2','Reason_3','Reason_4','Education']]
to_scale=x_train[[ 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index',
       'Children', 'Pets',]]

In [13]:
scaled_inputs=scaler.fit_transform(to_scale)

In [14]:
scaled_inputs

array([[ 1.5874065 , -0.24623737, -0.64169315, ...,  1.02422681,
        -0.9136046 , -0.59290048],
       [-1.1127382 , -0.24623737,  0.03701823, ..., -0.64035408,
        -0.008085  ,  1.07138157],
       [-1.41275428, -0.24623737, -0.64169315, ...,  1.02422681,
        -0.9136046 , -0.59290048],
       ...,
       [ 0.98737434, -1.37189394, -0.64169315, ..., -1.11594862,
         0.8974346 , -0.59290048],
       [ 1.28739042, -0.80906566,  0.83376637, ..., -0.64035408,
         0.8974346 , -0.59290048],
       [ 0.98737434,  0.31659091,  2.16167994, ..., -0.40255681,
         1.80295421, -0.59290048]])

In [15]:
dummies=dummies.to_numpy()


In [16]:
dummies.shape

(560, 5)

In [17]:
x_train=[]
x_train

[]

In [18]:
for i in range(dummies.shape[0]):
    x_train.append(np.concatenate((dummies[i],scaled_inputs[i])))
                   

In [19]:
x_train

[array([ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.5874065 , -0.24623737, -0.64169315,  1.4150028 ,  0.24268314,
        -0.44368337,  1.02422681, -0.9136046 , -0.59290048]),
 array([ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        -1.1127382 , -0.24623737,  0.03701823, -0.26523801, -1.29816217,
         1.76759454, -0.64035408, -0.008085  ,  1.07138157]),
 array([ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        -1.41275428, -0.24623737, -0.64169315,  1.4150028 ,  0.24268314,
        -0.49665241,  1.02422681, -0.9136046 , -0.59290048]),
 array([ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        -0.51270605, -1.37189394, -0.64169315,  1.4150028 ,  0.24268314,
         0.85362476,  1.02422681, -0.9136046 , -0.59290048]),
 array([ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        -1.71277036, -1.37189394,  0.37637392, -0.33244765,  1.62944392,
        -0.26169671,  

In [20]:
#x_train=np.array(x_train)

In [21]:
#x_train

In [22]:
#x_train=scaler.fit_transform(x_train)
#x_train

In [23]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [24]:
model.fit(x_train, y_train)

C:\Users\KurtandGrace\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
model.score(x_train,y_train)

0.7714285714285715

In [26]:
model.intercept_

array([-1.60415204])

In [27]:
model.coef_

array([[ 2.65657733,  0.65045647,  3.18646266,  0.79312759, -0.09528928,
        -0.0307237 , -0.18431558,  0.60266437, -0.07514183, -0.30059108,
         0.01585335,  0.23204093,  0.45423596, -0.31359925]])

In [28]:
summary_table=pd.DataFrame(columns=['Feature name'],data=x.columns.values)
summary_table

Feature name
0                  Reason_1
1                  Reason_2
2                  Reason_3
3                  Reason_4
4                 Education
5               Month Value
6           Day of the Week
7    Transportation Expense
8          Distance to Work
9                       Age
10  Daily Work Load Average
11          Body Mass Index
12                 Children
13                     Pets

In [29]:
summary_table['Coefficient'] = np.transpose(model.coef_)
summary_table=summary_table.sort_values('Coefficient')
summary_table

Feature name  Coefficient
13                     Pets    -0.313599
9                       Age    -0.300591
6           Day of the Week    -0.184316
4                 Education    -0.095289
8          Distance to Work    -0.075142
5               Month Value    -0.030724
10  Daily Work Load Average     0.015853
11          Body Mass Index     0.232041
12                 Children     0.454236
7    Transportation Expense     0.602664
1                  Reason_2     0.650456
3                  Reason_4     0.793128
0                  Reason_1     2.656577
2                  Reason_3     3.186463

In [30]:
summary_table['odds']=np.exp(summary_table.Coefficient)


In [31]:
summary_table=summary_table.sort_values('odds')
summary_table

Feature name  Coefficient       odds
13                     Pets    -0.313599   0.730812
9                       Age    -0.300591   0.740380
6           Day of the Week    -0.184316   0.831673
4                 Education    -0.095289   0.909110
8          Distance to Work    -0.075142   0.927612
5               Month Value    -0.030724   0.969743
10  Daily Work Load Average     0.015853   1.015980
11          Body Mass Index     0.232041   1.261171
12                 Children     0.454236   1.574970
7    Transportation Expense     0.602664   1.826980
1                  Reason_2     0.650456   1.916415
3                  Reason_4     0.793128   2.210299
0                  Reason_1     2.656577  14.247441
2                  Reason_3     3.186463  24.202663

In [32]:
test_dummies=x_test[['Reason_1','Reason_2','Reason_3','Reason_4','Education']]
test_to_scale=x_test[[ 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index',
       'Children', 'Pets',]]

In [33]:
test_scaled_inputs=scaler.transform(test_to_scale)

In [34]:
test_dummies=test_dummies.to_numpy()

In [35]:
x_test=[]
test_dummies.shape

(140, 5)

In [36]:
for i in range (test_dummies.shape[0]):
    x_test.append(np.concatenate((test_dummies[i],test_scaled_inputs[i])))

In [37]:
#x_test=scaler.transform(x_test)
#x_test

In [38]:
pred=model.predict(x_test)

In [39]:
from sklearn.metrics import classification_report,confusion_matrix

In [40]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.74      0.72      0.73        67
           1       0.75      0.77      0.76        73

    accuracy                           0.74       140
   macro avg       0.74      0.74      0.74       140
weighted avg       0.74      0.74      0.74       140



In [41]:
print(confusion_matrix(y_test,pred))

[[48 19]
 [17 56]]


In [42]:
model.score(x_train,y_train)

0.7714285714285715

In [43]:
import matplotlib.pyplot as plt
plt.scatter(y_test,pred)
plt.show()

<Figure size 640x480 with 1 Axes>

In [44]:
model.score(x_test,y_test)

0.7428571428571429